### ISSUE TITLE
"node.getSourceFile is not a function" error in Visual Studio Code

### ISSUE THREAD

**Issue by nicolashenry** [Microsoft/typescript-tslint-plugin#8]
I get this error in Typescript output console in Visual Studio Code when I click on a variable name once I add the plugin in tsconfig.json :

```
[Error  - 3:15:10 PM] 'occurrences' request failed with error.
Error processing request. node.getSourceFile is not a function
TypeError: node.getSourceFile is not a function
    at toHighlightSpan (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:96814:35)
    at Array.map (<anonymous>)
    at getSemanticDocumentHighlights (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:95528:59)
    at Object.getDocumentHighlights (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:95513:20)
    at getDocumentHighlights (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:114913:42)
    at Object.getOccurrencesAtPosition (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:114899:31)
    at Object.proxy.(anonymous function) [as getOccurrencesAtPosition] (l:\git\mobile\src\node_modules\typescript-tslint-plugin\out\index.js:67:33)
    at IOSession.Session.getOccurrences (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:122233:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:121766:61)
    at l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (l:\git\mobile\src\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Note that matching occurrences are not highlighted anymore when the error occurs.

I added this in tsconfig.json / compilerOptions :
```json
"plugins": [
      {
        "name": "typescript-tslint-plugin",
        "suppressWhileTypeErrorsPresent": true
      }
    ]
```

I am using Typescript 3.1.3 (Workspace Version) with Visual Studio Code 1.28.2.

**Comment by nicolashenry** [comment]
I found out that each of these three rules are causing the error : 
https://github.com/cartant/rxjs-tslint-rules/blob/v4.10.0/source/rules/rxjsNoUnboundMethodsRule.ts
https://github.com/cartant/rxjs-tslint-rules/blob/v4.10.0/source/rules/rxjsPreferObserverRule.ts
https://github.com/cartant/rxjs-tslint-rules/blob/v4.10.0/source/rules/rxjsNoNestedSubscribeRule.ts

If I disable these three rules, there is not "'occurrences' request failed with error." errors anymore.

**Comment by mjbvz** [comment]
Are you sure this plugin is the root cause? Does this happen when the plugin is disabled.

We don't really touch the `getOccurrences` call path. The proxy just passes the call through to standard ts implementation

**Comment by nicolashenry** [comment]
It does not happen when the plugin is disabled or when the rxjs-tslint-rules rules are disabled. I think that what rxjs-tslint-rules does with typescript program is the root cause but I am not an expert with tslint.

**Comment by nicolashenry** [comment]
Here is a minimal reproduction case : 

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "rxjs-tslint-rules": "^4.10.0",
    "tslint": "^5.11.0",
    "typescript": "^3.1.3",
    "typescript-tslint-plugin": "0.0.4"
  }
}
```
tsconfig.json
```json
{
	"compilerOptions": {
		"target": "es5",
		"module": "es2015",
		"lib": [
			"es2017",
			"dom"
		],
		"moduleResolution": "node",
		"esModuleInterop": true,
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"forceConsistentCasingInFileNames": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"strict": true,
		"removeComments": true,
		"allowSyntheticDefaultImports": true,
		"noImplicitReturns": true,
		"importHelpers": true,
		"pretty": true,
		"typeRoots": ["./node_modules/@types"],
		"types": [],
		"plugins": [{
			"name": "typescript-tslint-plugin",
			"suppressWhileTypeErrorsPresent": true
		}]
	}
}
```
tslint.json
```json
{
	"defaultSeverity": "warning",
	"linterOptions": {
		"exclude": [
			"node_modules/**",
			"dist/**"
		]
	},
	"rulesDirectory": [
		"node_modules/rxjs-tslint-rules/dist/rules"
	],
	"rules": {
		"rxjs-no-unbound-methods": true,
		"rxjs-prefer-observer": true,
		"rxjs-no-nested-subscribe": true
	}
}
```
index.ts
```ts

const test = "test";
console.log(test);

```

**Comment by nicolashenry** [comment]
@mjbvz Did you reproduce the issue?

I think that this is maybe caused by the "@phenomnomnominal/tsquery" module used by "rxjs-tslint-rules" in some rules which seems to modify typescript nodes [here](https://github.com/phenomnomnominal/tsquery/blob/b860737c82471a130042fb1df80c0abe12799b45/src/traverse.ts#L63).

I am not sure that you can do anything about the issue in this plugin but it would be nice to have a way to detect/prevent problematic rules since the issue only occurs when this plugin is used.

**Comment by mjbvz** [comment]
This is an external issue with that rule. As a tsserver plugin, there is unfortunately nothing we can do to detect or prevent this

Please try filing an issue against those rules
